image: "fedora:39"

variables:
  RUST_BACKTRACE: "full"
  RUSTFLAGS: "--verbose"

before_script:
  - dnf install -y desktop-file-utils cargo gtk4-devel libadwaita-devel libappstream-glib make

test:
  script:
    - make
    - make check
