image: "fedora:39"

before_script:
  - dnf install -y cargo gtk4-devel libadwaita-devel

test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose
