[package]
name = "startup-disk"
version = "0.1.6"
authors = ["Davide Cavalca <davide@cavalca.name>"]
edition = "2021"
repository = "https://gitlab.gnome.org/davide125/startup-disk.git"
homepage = "https://gitlab.gnome.org/davide125/startup-disk"
license = "MIT"
documentation = "https://gitlab.gnome.org/davide125/startup-disk"
description = "Interface to choose the startup volume on Apple Silicon systems"
categories = ["hardware-support"]
keywords = ["gnome", "asahi"]

[dependencies]
adw = { version = "0.8", package = "libadwaita", features = ["v1_8"] }
asahi-bless = "0.4.2"
gtk = { version = "0.10", package = "gtk4", features = ["gnome_49"] }
nix = { version = "0.31.1", features = ["user"] }
rand = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
uuid = { version = "1.21", features = ["serde"] }

[build-dependencies]
glib-build-tools = "0.20.0"
